default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: 127.0.0.1
  database: sixthstreet
  username: radio
  password: <%= ENV['MYSQL_PASSWORD'] %>

